<a href="https://colab.research.google.com/github/juliosdutra/FundamentosComputacionais/blob/main/Estruturas_basicas.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Estruturas de Programação

No Python (e em qualquer linguagem de programação), estruturas de programação são os blocos fundamentais usados para controlar o fluxo e a organização do código. Elas permitem:

* **Importar bibliotecas (com import, para reutilizar código existente)**

* **Armazenar dados (com variáveis)**,

* Tomar decisões (com estruturas condicionais),

* Executar tarefas repetidamente (com laços de repetição),

*  Organizar o código em partes reutilizáveis (com funções).

Por hora, vamos focar nos dois primeiros itens.

## Importar bibliotecas

In [131]:
# Importando as bibiliotecas padrão
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd
from scipy import linalg

In [132]:
# Instalando uma biblioteca e em seguida importar
!pip install -qq control
import control as ct

In [190]:
# Funções matemáticas

print(np.pi)            # pi
print(np.exp(1))        # e

print(5 % 2)

print(np.random.rand(1))
print(np.random.sample(5))

3.141592653589793
2.718281828459045
1
[0.48883017]
[0.7646054  0.30445988 0.36545666 0.5876934  0.70583785]


## Atribuição de variáveis

In [ ]:
# atribuição simples
x = 3.14

# atribuição ao mesmo valor
a = b = c = 5

# atribuição múltipla
Kc, Ki, tipo = -0.9, 10, "PI"

# Imprimir os valores
print("x =", x)
print("a =", a, "b =", b, "c =", c)
print("Kc =", Kc, "Ki =", Ki, "tipo =", tipo)

x = 3.14
a = 5 b = 5 c = 5
Kc = -0.9 Ki = 10 tipo = PI


In [ ]:
# troca de valores
a, x = x, a
print("a =", a, "x =", x)

a = 3.14 x = 5


In [ ]:
# descompactação de sequências em um item ou lista
lista = [1, 2, 3, 4, 5]
r, *s = lista
*v, w = lista

print("r =", r, "s =", s)
print("v =", v, "w =", w)

r = 1 s = [2, 3, 4, 5]
v = [1, 2, 3, 4] w = 5


In [ ]:
# incremento de um valor
x += 1
print("x =", x)

x = 6


## Tipos de dados

### Dadosprimitivos

In [ ]:
inteiro = 10
real = 3.14
complexo = 2 + 3j
string = "Olá, mundo!"
booleano = True  # ou False

In [ ]:
NumeroInteiro = int(3.14)
NumeroReal = float(1)
NumeroComplexo = complex(5,1.15)
Caracteres = str(2025)
Verificador = bool(0)

print('NumeroInteiro = ', NumeroInteiro, type(NumeroInteiro))
print('NumeroReal = ', NumeroReal, type(NumeroReal))
print('NumeroComplexo = ', NumeroComplexo, type(NumeroComplexo))
print('Caracteres = ', Caracteres, type(Caracteres))
print('Verificador = ', Verificador, type(Verificador))

NumeroInteiro =  3 <class 'int'>
NumeroReal =  1.0 <class 'float'>
NumeroComplexo =  (5+1.15j) <class 'complex'>
Caracteres =  2025 <class 'str'>
Verificador =  False <class 'bool'>


Aqui estão alguns exemplos para ilustrar a soma de inteiros, multiplicação de floats e concatenação de strings:

In [ ]:
# Soma de inteiros (int):
inteiro1 = 10
inteiro2 = 5
soma = inteiro1 + inteiro2
print("A soma dos inteiros é:", soma)
# Saída: A soma dos inteiros é: 15

A soma dos inteiros é: 15


In [ ]:
# Multiplicação de reais (float):
real1 = 3.14
real2 = 2.5
multiplicacao = real1 * real2
print("A multiplicação dos floats é:", multiplicacao)
# Saída: A multiplicação dos floats é: 7.85

A multiplicação dos floats é: 7.8500000000000005


A soma entre um inteiro e um float resulta em um float,pois a operação entre tipos mistos converte o inteiro para float para garantir maior precisão.

In [ ]:
# Definindo variáveis
inteiro = 1
real = 3.14
print("O resultado da soma é:", inteiro+real)
print("O resultado da multiplicação é:", inteiro*real)
print("O resultado da pontência é:", inteiro**real)

O resultado da soma é: 4.140000000000001
O resultado da multiplicação é: 3.14
O resultado da pontência é: 1.0


In [ ]:
# Concatenação de strings (str):
# Solicitar nome do usuário
nome = "Ana Maria"

# Solicitar idade do usuário
idade = "23"

# Criar uma mensagem usando concatenação
mensagem = "Olá, " + nome + "! Você tem " + str(idade) + " anos."

# Alternativa com formatação f-string (mais elegante)
mensagem_formatada = f"Olá, {nome}! Você tem {idade} anos."

# Exibir as mensagens
print(mensagem)
print(mensagem_formatada)

Olá, Ana Maria! Você tem 23 anos.
Olá, Ana Maria! Você tem 23 anos.


Resumo sobre os métodos para usar com strings:

In [ ]:
texto = "Olá, Mundo! Mundo!"

print('Texto em letras maiúsculas:', texto.upper())
print('Texto em letras maiúsculas:', texto.lower())
print('Total de caracteres:', len(texto))
print('Total de ocorrências de Mundo:', texto.count('Mundo'))

### Estruturas Compostas


In [141]:
# Lista de strings
composto = ['CO2', 'H20', 'N2']

# Lista numérica
analise = [46, 18, 28]

print('Número de compostos = ', len(composto))
print('Lista de compostos = ', composto)
print('Dados de analise = ', analise)

Número de compostos =  3
Lista de compostos =  ['CO2', 'H20', 'N2']
Dados de analise =  [46, 18, 28]


In [139]:
# Mapeamento (associação) entre as duas listas
map = zip(composto, analise)

# Geração automática de um dicionário
massa = dict(map)

massa['CO2']

46

In [121]:
# Lista
reatores = ["CSTR", "PFR", "Batch"]
print('Lista 0:', reatores)

# Adicionar um novo tipo de reator, o "UASB", à lista.
reatores.append("UASB")
print('Lista 1:', reatores)

# Adicionar um outro tipo de reator, o "PBR", antes da posição 1.
reatores.insert(1, "PBR")
print('Lista 2:', reatores)

# Remover o tipo de reator "PFR" da lista.
reatores.remove("PFR")
print('Lista 3:', reatores)

# Remover o tipo de reator "CSTR" da lista.
reatores.pop(0)
print('Lista 4:', reatores)

Lista 0: ['CSTR', 'PFR', 'Batch']
Lista 1: ['CSTR', 'PFR', 'Batch', 'UASB']
Lista 2: ['CSTR', 'PBR', 'PFR', 'Batch', 'UASB']
Lista 3: ['CSTR', 'PBR', 'Batch', 'UASB']
Lista 4: ['PBR', 'Batch', 'UASB']


Arrays (vetores e matrizes)

In [149]:
import numpy as np

v = np.array([1 ,2 ,3])
w = np.array([4, 5 , 6])

print('Vetor v = ', v)
print('Dimensão de v =', v.shape)
print('Tipo de dado = ', type(v))

Vetor v =  [1 2 3]
Dimensão de v = (3,)
Tipo de dado =  <class 'numpy.ndarray'>


In [153]:
# Concatenar vetores
v0 = np.array([-1, 0])
v_aumentado = np.hstack([v, v0])

print(v_aumentado)
print('Dimensão nova =', v_aumentado.shape)

[ 1  2  3 -1  0]
Dimensão nova = (5,)


In [154]:
v2 = np.array([10, 100, 1000])
matriz_v = np.vstack([v, v2])

print(matriz_v)
print('Dimensão da matriz =', matriz_v.shape)

[[   1    2    3]
 [  10  100 1000]]
Dimensão da matriz = (2, 3)


In [161]:
# Importando as bibliotecas necessárias
import numpy as np
from scipy.linalg import det

# Criando a matriz A
A = np.array([ [1 , 2, 3],
               [0 ,-1, 1],
               [5, 0, 4]])

print("Matriz A = \n", A)
print('Dimensão da matriz =', A.shape)
print('Determinando da matriz =', det(A))

Matriz A = 
 [[ 1  2  3]
 [ 0 -1  1]
 [ 5  0  4]]
Dimensão da matriz = (3, 3)
Determinando da matriz = 21.0


Operação com escalares e outros vetores/matrizes


In [166]:
v1 = np.array([1, 2, 3], dtype='float')

v2 = 3*v1 +1

v2

array([ 4.,  7., 10.])

In [167]:
A = np.array([ [1 , 2, 3],
               [0 ,-1, 1],
               [5, 0, 4]])

B = A**2 - 3*A +1

B

array([[-1, -1,  1],
       [ 1,  5, -1],
       [11,  1,  5]])

In [168]:
C = A @ v1
C

array([14.,  1., 17.])

Sequência de números

In [169]:
# range(início, fim, passo)
sequencia1 = range(0,10) # de 0 a 10 (exclusivo), com passo 1
print(list(sequencia1))

sequencia2 = range(0,10,2) # de 0 a 10 (exclusivo), com passo 2
print(list(sequencia2))

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]
[0, 2, 4, 6, 8]


In [171]:
np.arange(0,10,2.5)

array([0. , 2.5, 5. , 7.5])

In [172]:
np.linspace(0,1,11)

array([0. , 0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9, 1. ])

Indexação dos elementos

In [179]:
A = np.random.random((3,4))
A

array([[0.33131038, 0.71755769, 0.60180884, 0.09931208],
       [0.84401996, 0.54740509, 0.31605709, 0.05128247],
       [0.68857399, 0.58081946, 0.34979214, 0.61374949]])

In [180]:
# Elemento A[2,3]
A[2,3]

np.float64(0.61374948798518)

In [181]:
# Bloco
A[1:3,1:4]

array([[0.54740509, 0.31605709, 0.05128247],
       [0.58081946, 0.34979214, 0.61374949]])

In [182]:
# todos elementos da primeira linha
A[0,:]

array([0.68857399, 0.58081946, 0.34979214, 0.61374949])

In [183]:
# todos elementos da última coluna
A[:,-1]

array([0.09931208, 0.05128247, 0.61374949])

Vetorização

In [186]:
A = np.random.rand(2,2)
A

array([[0.59710538, 0.00608318],
       [0.98847236, 0.96489521]])

In [187]:
A.flatten()

array([0.59710538, 0.00608318, 0.98847236, 0.96489521])

In [188]:
A.flatten('F')

array([0.59710538, 0.98847236, 0.00608318, 0.96489521])